### ISSUE TITLE
simplebot init fails with "AssertionError: plugin is not registered"

### ISSUE THREAD

**Issue by sysfu** [simplebot-org/simplebot#144]
I'm following the guide posted in the Delta Chat support forum [here](https://support.delta.chat/t/how-to-set-up-a-delta-bot-in-6-steps/1170/1).

After attempting to initialize the bot it fails with the "AssertionError: plugin is not registered" traceback.

I have reproduced this issue on gentoo, guix and ubuntu systems which have the latest updates.

```
$ simplebot --stdlog debug init $ADDR "$PASSWORD"
2023-11-27 13:57:56,965 - simplebot - DEBUG - registering plugin 'commands'
2023-11-27 13:57:56,965 - simplebot - DEBUG - registering plugin 'filters'
2023-11-27 13:57:56,982 - simplebot - DEBUG - registering plugin 'db'
2023-11-27 13:57:56,982 - simplebot - DEBUG - registered new command '/sub'
2023-11-27 13:57:56,982 - simplebot - DEBUG - registered new command '/unsub'
2023-11-27 13:57:56,983 - simplebot - DEBUG - registered new command '/help'
2023-11-27 13:57:56,983 - simplebot - DEBUG - registered new command '/unban'
2023-11-27 13:57:56,983 - simplebot - DEBUG - registered new command '/ban'
2023-11-27 13:57:56,983 - simplebot - DEBUG - registered new command '/set'
2023-11-27 13:57:56,983 - simplebot - DEBUG - registered new command '/echo'
2023-11-27 13:57:56,983 - simplebot - DEBUG - registered new filter 'simplebot_echo.echo_filter'
2023-11-27 13:58:58,034 - simplebot - INFO - Successfully configured bot@domain.tld
Traceback (most recent call last):
  File "/home/user/.local/bin/simplebot", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/user/.local/lib/python3.11/site-packages/simplebot/main.py", line 24, in main
    parser.main_run(bot=bot, args=args)
  File "/home/user/.local/lib/python3.11/site-packages/simplebot/parser.py", line 111, in main_run
    res = args.subcommand_instance.run(**kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.local/lib/python3.11/site-packages/simplebot/builtin/cmdline.py", line 152, in run
    success = bot.perform_configure_address(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.local/lib/python3.11/site-packages/simplebot/bot.py", line 383, in perform_configure_address
    with self.account.temp_plugin(tracker) as configtracker:
  File "/usr/lib/python3.11/contextlib.py", line 144, in __exit__
    next(self.gen)
  File "/home/user/.local/lib/python3.11/site-packages/deltachat/account.py", line 671, in temp_plugin
    self._pm.unregister(plugin)
  File "/usr/lib/python3.11/site-packages/pluggy/_manager.py", line 206, in unregister
    assert name is not None, "plugin is not registered"
           ^^^^^^^^^^^^^^^^
AssertionError: plugin is not registered
```

**Comment by nudeldudel** [comment]
Me too.

**Comment by dillfrescott** [comment]
Same

**Comment by adbenitez** [comment]
hello, (sorry the late reply @sysfu, @nudeldudel) I fixed the issue, sadly the CI failed to publish the new release apparently because pypi is under spam attack or something like that, what a bad timing, anyway you can update your simplebot directly from this repository:

```
pip install -U git+https://github.com/simplebot-org/simplebot
```

then try again and the `simplebot init` step will work now

**note:** if you are looking into creating new bots, don't use simplebot library, use this library instead: https://github.com/deltachat-bot/deltabot-cli-py, only use simplebot if your intention is to host some bot with a simplebot plugin that already exist
